name: CI pipline

on: 
  push:
    branches:
      -main
  pull-request:
    branches:
      -main
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4

    #- name: Install depencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install -r requirements

    #- name: Run migrations
    #  run: |
    #    python manage.py migrate

    #- name: Run tests
    #    run: |
    #      python manage.py test 
